robot:
  root_link: elfin_base_link
  tip_link: elfin_end_link

  control_point_names:

    - elfin_link3
    - elfin_link4
    - elfin_link5
    - elfin_link6

    - elfin_link2_a
    - elfin_link2_b
    - elfin_link3_a
    - elfin_link4_a

    - elfin_link4_b
    - elfin_link4_c
  control_point_radiuses:
    - 0.08
    - 0.085
    - 0.085
    - 0.09
    
    - 0.06
    - 0.06
    - 0.07
    - 0.06

    - 0.06
    - 0.05
solver:
  spacing: 0.002
  maxnorm: 0.1
  merge_attempt_interval: 500
  maxiter: 5000

obstacles:
  x:
    - 0.22


  y:
    - 0


  z:
    - 0.6


  r:
    - 0.05


    