robot:
  root_link: elfin_base_link
  tip_link: elfin_end_link

  control_point_names:
    - elfin_link1
    - elfin_link2
    - elfin_link3
    - elfin_link4
    - elfin_link5
    - elfin_link6
    - elfin_end_link
  control_point_radiuses:
    - 0.09
    - 0.09
    - 0.09
    - 0.09
    - 0.09
    - 0.09
    - 0.02
solver:
  spacing: 0.002
  maxnorm: 0.1
  merge_attempt_interval: 500
  maxiter: 5000

obstacles:
  x:
    - 0.22
  y:
    - 0
  z:
    - 0.6
  r:
    - 0.05
    